name: Deploy Fullstack App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      # ------------------------------
      # BACKEND SETUP
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci

      - name: Create backend .env file
        working-directory: ./server
        run: |
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Start backend with PM2
        working-directory: ./server
        run: |
          /home/ubuntu/.nvm/versions/node/v22.23.2/bin/pm2 restart backend || /home/ubuntu/.nvm/versions/node/v22.23.2/bin/pm2 start index.js --name backend

      # ------------------------------
      # FRONTEND SETUP
      # ------------------------------
      - name: Clean frontend dependencies
        working-directory: ./client
        run: |
          rm -rf node_modules

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm ci

      # Uncomment if your React app requires environment variables
      # - name: Create frontend .env file
      #   working-directory: ./client
      #   run: |
      #     echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Verify ESLint versions
        working-directory: ./client
        run: |
          npm ls eslint
          npm ls eslint-config-react-app
          npm ls eslint-plugin-jest

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Deploy frontend to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r ./client/build/* /var/www/html/
          sudo systemctl reload nginx
